import Head from "next/head";
import { SocialIcon } from "../components/SocialIcon";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ background: "black" }}>
        <SocialIcon size={64} platform="twitter" inverse />
        <SocialIcon size={64} platform="github" />
        <SocialIcon size={64} platform="discord" />
      </main>
    </>
  );
}
